#Abhiram Krishnakumar 7/13/2025 Challenging Level Hackathon

# This is using requests, a python library that allows python to make http requests (https://pypi.org/project/requests/)
#The food data (stored in the json files) is generated by CHATGPT. However, CHATGPT was not used for any code.
import json
from internal_code import *

#Load the JSON Files
breakfast = json.load(open("food_items/breakfast.json"))
lunch = json.load(open("food_items/lunch.json"))
dinner = json.load(open("food_items/dinner.json"))
grander_food = json.load(open("food_items/grander_items.json"))

#Initialize the sample diet
person = DietaryRestrictions(vegan = False, 
                             iron_rich = False,
                             egg = True,
                             nuts = True,
                             dairy = True,
                             meat = True,
                             meals = 3,
                             low_sugar = False,
                             high_fiber = False,
                             gluten_free = False,
                             max_cal = 2000,
                             budget = 100,
                             special_occasion = False,
                             )
                             
print('***********************\n\n\n')
print(person.get_foods(breakfast, lunch, dinner, grander_food))
 
if __name__ == "__main__" :
    instance = Mealy()
    instance.run()
